version: '2'

services:
  web:
    build: .
    volumes:
     - ./proxys.template:/etc/nginx/conf.d/proxys.template
     - ./private/dev.key:/etc/nginx/private/dev.key
     - ./private/dev.pem:/etc/nginx/private/dev.pem

    ports:
     - "127.0.0.1:7070:80"
    command: /bin/sh -c "envsubst '$$DEV_DOMAIN $$DNS_NAME $$NGINX_PORT $$PROXY_TO_IP $$ACTAS' < /etc/nginx/conf.d/proxys.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - DNS_NAME=docker.internal
      - NGINX_PORT=80
      - PROXY_TO_IP=${PROXY_TO_IP}
      - ACTAS=${ACT_AS}
      - DEV_DOMAIN=${DEV_DOMAIN}
