version: '2'

services:
  web:
    image: nginx:1.15.3
    volumes:
     - ./proxys.template:/etc/nginx/conf.d/proxys.template
    ports:
     - "7070:80"
    command: /bin/sh -c "envsubst '$$DNS_NAME $$NGINX_PORT $$PROXY_TO_IP $$ACTAS' < /etc/nginx/conf.d/proxys.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - DNS_NAME=docker.internal
      - NGINX_PORT=80
      - PROXY_TO_IP=${PROXY_TO_IP}
      - ACTAS=maximed